export enum EquipmentType {
  COMPUTADOR = "COMPUTADOR", 
  NOTEBOOK = "NOTEBOOK", 
  MONITOR = "MONITOR",
  IMPRESSORA = "IMPRESSORA",
  TECLADO = "TECLADO",
  MOUSE = "MOUSE",
  FONE_OUVIDO = "FONE_OUVIDO",
  CELULAR = "CELULAR",
  OUTROS = "OUTROS"
}